.PHONY: clean run_client run_server

clean:
    @echo "Limpiando archivos compilados..."
    @rm -f cliente servidor
    @echo "Archivos compilados eliminados."

run_client:
    @echo "Ejecutando cliente..."
    @python3 cli4.py

run_server:
    @echo "Ejecutando servidor..."
    @python3 serv4.py
